//"use client";
import { SignUpProvider } from "./Context/SignUpContext";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SignUpProvider>
          {children}
        </SignUpProvider>
      </body>
    </html>
  );
}
